# Docker build configuration
platforms: linux/amd64,linux/arm64

# Docker metadata configuration
metadata:
  images: |
    ghcr.io/${{ github.repository }}
  tags: |
    type=ref,event=branch
    type=ref,event=pr
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=raw,value=latest,enable={{is_default_branch}}

# Docker build arguments
build-args: |
  PYTHON_VERSION=3.12
  BUILD_DATE={{date 'YYYY-MM-DD'}}
  VCS_REF={{sha}}

# Cache configuration
cache:
  from: type=gha
  to: type=gha,mode=max